source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MCSwipeTransition_Example', :exclusive => true do
  pod 'MCSwipeTransition', :path => '../'
end

target 'MCSwipeTransition_Tests', :exclusive => true do
  pod 'MCSwipeTransition', :path => '../'

  
end
